name: Auto trigger CodeRabbit

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  trigger-coderabbit:
    runs-on: ubuntu-latest
    steps:
      - name: Comment to trigger CodeRabbit review
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@coderabbitai review"
            }) 
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}