name: Auto PR Summary with Gemini

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_and_update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Post CodeRabbit review comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.MY_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "@coderabbitai review"

      - name: Wait for CodeRabbit summary
        id: wait_for_comment
        run: |
          echo "Polling for CodeRabbit summary comment..."
          SUMMARY_FILE=$(mktemp)
          
          for i in {1..30}; do
            echo "Polling attempt $i..."
            sleep 30
            
            COMMENTS=$(gh api repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments)
            
            echo "$COMMENTS" | jq -r '.[] | select(.user.login=="coderabbitai[bot]" and .body and (.body | contains("<!-- walkthrough_start -->"))) | .body' > "$SUMMARY_FILE"

            if [[ -s "$SUMMARY_FILE" ]]; then
              echo "Found CodeRabbit summary comment."
              echo "summary<<EOF" >> $GITHUB_OUTPUT
              cat "$SUMMARY_FILE" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
              rm "$SUMMARY_FILE"
              exit 0
            else
              echo "CodeRabbit summary comment not found yet. (Waiting for the actual summary...)"
            fi
          done

          echo "Timed out waiting for CodeRabbit summary comment."
          rm "$SUMMARY_FILE"
          exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Generate PR body using Gemini API
        id: generate_pr_body
        run: |
          # PRテンプレートが存在すれば読み込む
          if [ -f ".github/PULL_REQUEST_TEMPLATE.md" ]; then
            PR_TEMPLATE=$(cat .github/PULL_REQUEST_TEMPLATE.md)
          else
            PR_TEMPLATE=""
          fi
          
          # ★★★ 変更点 ★★★
          # printf を使わず、ヒアドキュメントで安全にプロンプトを組み立てる。
          # これにより、巨大なSUMMARY変数がコマンドとして解釈されるのを防ぐ。
          read -r -d '' FULL_PROMPT << EOF
          以下はGitHubのプルリクエストに対するAIレビューコメントです。この内容をもとに、下記のPRテンプレートの「変更内容」と「実装の背景」欄を作成してください。

          【AIレビューコメント】
          ${{ steps.wait_for_comment.outputs.summary }}

          【PRテンプレート】
          $PR_TEMPLATE

          # 出力条件
          - PRテンプレートの「### 変更内容」と「### 実装の背景」のセクションを、AIレビューコメントを参考にして埋めてください。
          - 他のセクション（「### この実装のゴール」や「チェックリスト」など）は、テンプレートの形式を維持したまま、中身は空欄にしてください。
          - 全体として、元のPRテンプレートの構造を維持した形で出力してください。
          - 余計な挨拶や説明文は不要です。
          EOF

          JSON_PAYLOAD=$(jq -n \
            --arg prompt "$FULL_PROMPT" \
            '{contents: [{parts: [{text: $prompt}]}]}')

          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD")

          BODY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          
          if [ -z "$BODY" ] || [ "$BODY" == "null" ]; then
            echo "::error::Failed to extract body from Gemini response. The response might be empty or blocked."
            exit 1
          fi

          echo "pr_body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Update PR body
        run: |
          echo "Updating PR body..."
          # マルチラインの本文を安全に更新するために --body-file を使用
          gh pr edit ${{ github.event.pull_request.number }} --body-file <(echo "${{ steps.generate_pr_body.outputs.pr_body }}")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}